from django.utils.translation import gettext_lazy as _
from django.db import models

class IconChoices(models.TextChoices):
    AMAZON = "Amazon", _("Amazon")
    ANDRIOD_PLAY_STORE = "Andriod Play Store", _("Andriod Play Store")
    APPLE_PLAY_STORE = "Apple Play Store", _("Apple Play Store")
    APPLE_MUSIC = "Apple Music", _("Apple Music")
    APPLE_PODCAST = "Apple Podcast", _("Apple Podcast")
    BANDCAMP = "Bandcamp", _("Bandcamp")
    CLUBHOUSE = "Clubhouse", _("Clubhouse")
    DISCORD = "Discord", _("Discord")
    EMAIL = "Email", _("Email")
    ETSY = "Etsy", _("Etsy")
    FACEBOOK = "Facebook", _("Facebook")
    INSTAGRAM = "Instagram", _("Instagram")
    LINKEDIN = "Linkedin", _("Linkedin")
    PATREON = "Patreon", _("Patreon")
    PAYMENT = "Payment", _("Payment")
    PINTEREST = "Pinterest", _("Pinterest")
    SIGNAL = "Signal", _("Signal")
    SNAPCHAT = "Snapchat", _("Snapchat")
    SOUNDCLOUD = "Soundcloud", _("Soundcloud")
    SPOTIFY = "Spotify", _("Spotify")
    SUBSTACK = "Substack", _("Substack")
    TELEGRAM = "Telegram", _("Telegram")
    TIKTOK = "Tiktok", _("Tiktok")
    TWITCH = "Twitch", _("Twitch")
    TWITTER = "Twitter", _("Twitter")
    WHATSAPP = "WhatsApp", _("WhatsApp")
    YOUTUBE = "Youtube", _("Youtube")
    GITHUB = "Github", _("Github")