# Generated by Django 4.2.2 on 2023-07-12 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Amazon', 'Amazon'), ('Andriod Play Store', 'Andriod Play Store'), ('Apple Play Store', 'Apple Play Store'), ('Apple Music', 'Apple Music'), ('Apple Podcast', 'Apple Podcast'), ('Bandcamp', 'Bandcamp'), ('BeReal', 'BeReal'), ('Cameo', 'Cameo'), ('Clubhouse', 'Clubhouse'), ('Discord', 'Discord'), ('Email', 'Email'), ('Etsy', 'Etsy'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Patreon', 'Patreon'), ('Payment', 'Payment'), ('Pinterest', 'Pinterest'), ('Poshmark', 'Poshmark'), ('Signal', 'Signal'), ('Snapchat', 'Snapchat'), ('Soundcloud', 'Soundcloud'), ('Spotify', 'Spotify'), ('Substack', 'Substack'), ('Telegram', 'Telegram'), ('Tiktok', 'Tiktok'), ('Twitch', 'Twitch'), ('Twitter', 'Twitter'), ('WhatsApp', 'WhatsApp'), ('Youtube', 'Youtube'), ('Github', 'Github')], max_length=100, null=True, verbose_name='icon')),
                ('url', models.URLField(null=True, verbose_name='url')),
                ('is_added', models.BooleanField(default=False, verbose_name='icon added status')),
                ('is_visible', models.BooleanField(default=True, verbose_name='social icon visibility status')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Icon',
                'verbose_name_plural': 'Social Icons',
            },
        ),
        migrations.CreateModel(
            name='SeoMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, max_length=165, null=True, verbose_name='description')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_meta_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seo Meta Data',
                'verbose_name_plural': 'Seo Meta Data',
            },
        ),
    ]
