# Generated by Django 4.2.2 on 2023-07-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='aliase',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='icon aliase name'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Andriod Play Store', 'Andriod Play Store'), ('Apple Play Store', 'Apple Play Store'), ('Apple Music', 'Apple Music'), ('Apple Podcast', 'Apple Podcast'), ('Bandcamp', 'Bandcamp'), ('Clubhouse', 'Clubhouse'), ('Discord', 'Discord'), ('Email', 'Email'), ('Etsy', 'Etsy'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Patreon', 'Patreon'), ('Payment', 'Payment'), ('Pinterest', 'Pinterest'), ('Signal', 'Signal'), ('Snapchat', 'Snapchat'), ('Soundcloud', 'Soundcloud'), ('Spotify', 'Spotify'), ('Substack', 'Substack'), ('Telegram', 'Telegram'), ('Tiktok', 'Tiktok'), ('Twitch', 'Twitch'), ('Twitter', 'Twitter'), ('WhatsApp', 'WhatsApp'), ('Youtube', 'Youtube'), ('Github', 'Github')], max_length=100, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='is_added',
            field=models.BooleanField(default=True, verbose_name='icon added status'),
        ),
    ]
