# Generated by Django 4.2.2 on 2023-07-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_sociallink_aliase_alter_sociallink_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='readable english name')),
                ('icon', models.CharField(max_length=255, null=True, unique=True, verbose_name='actual react-icons name')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
    ]
