# Generated by Django 4.2.2 on 2023-07-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_icons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icons',
            new_name='Icon',
        ),
    ]
