# Generated by Django 4.2.2 on 2023-07-03 00:52

from django.db import migrations, models
import utils.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('is_visible', models.BooleanField(default=True, verbose_name='link visibility status')),
                ('url_thumbnail', models.URLField(blank=True, null=True, verbose_name='url reference thumbnail')),
                ('upload_thumbnail', models.ImageField(blank=True, null=True, upload_to=utils.upload.upload_thumbnail_to, verbose_name='uploaded thumbnail')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
