# Generated by Django 4.2.2 on 2023-07-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='go_live_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='schedule link to go live'),
        ),
    ]
