export const Icons = [
    { name: "Amazon", icon: "PiAmazonLogoLight" },
    { name: "Andriod Play Store", icon: "PiGooglePlayLogoLight" },
    { name: "Apple Play Store", icon: "GrAppleAppStore" },
    { name: "Apple Music", icon: "PiMusicNotesLight" },
    { name: "Apple Podcast", icon: "PiApplePodcastsLogoLight" },
    { name: "Bandcamp", icon: "LiaBandcamp" },
    { name: "Clubhouse", icon: "PiHandWavingLight" },
    { name: "Discord", icon: "PiDiscordLogoLight" },
    { name: "Email", icon: "PiEnvelopeLight" },
    { name: "Etsy", icon: "FaEtsy" },
    { name: "Facebook", icon: "PiFacebookLogoLight" },
    { name: "Instagram", icon: "PiInstagramLogoLight" },
    { name: "Linkedin", icon: "FiLinkedin" },
    { name: "Patreon", icon: "PiPatreonLogoLight" },
    { name: "Payment", icon: "PiCurrencyCircleDollarLight" },
    { name: "Pinterest", icon: "PiPinterestLogoLight" },
    { name: "Signal", icon: "BsSignal" },
    { name: "Snapchat", icon: "PiSnapchatLogoLight" },
    { name: "Soundcloud", icon: "PiSoundcloudLogoLight" },
    { name: "Spotify", icon: "PiSpotifyLogoLight" },
    { name: "Substack", icon: "SiSubstack" },
    { name: "Telegram", icon: "PiTelegramLogoLight" },
    { name: "Tiktok", icon: "PiTiktokLogoLight" },
    { name: "Twitch", icon: "PiTwitchLogoLight" },
    { name: "Twitter", icon: "PiTwitterLogoLight" },
    { name: "WhatsApp", icon: "PiWhatsappLogoLight" },
    { name: "Youtube", icon: "PiYoutubeLogoLight" },
    { name: "Github", icon: "PiGithubLogoLight" },
];