# Generated by Django 4.2.2 on 2023-07-03 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='username')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatar_images/default.jpg', help_text='profile picture', null=True, upload_to=utils.upload.upload_avatar_to, verbose_name='avatar')),
                ('title', models.CharField(help_text='profile title', max_length=100, null=True, verbose_name='title')),
                ('bio', models.CharField(help_text='about user', max_length=80, null=True, verbose_name='bio')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Amazon', 'Amazon'), ('Andriod Play Store', 'Andriod Play Store'), ('Apple Play Store', 'Apple Play Store'), ('Apple Music', 'Apple Music'), ('Apple Podcast', 'Apple Podcast'), ('Bandcamp', 'Bandcamp'), ('BeReal', 'BeReal'), ('Cameo', 'Cameo'), ('Clubhouse', 'Clubhouse'), ('Discord', 'Discord'), ('Email', 'Email'), ('Etsy', 'Etsy'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Patreon', 'Patreon'), ('Payment', 'Payment'), ('Pinterest', 'Pinterest'), ('Poshmark', 'Poshmark'), ('Signal', 'Signal'), ('Snapchat', 'Snapchat'), ('Soundcloud', 'Soundcloud'), ('Spotify', 'Spotify'), ('Substack', 'Substack'), ('Telegram', 'Telegram'), ('Tiktok', 'Tiktok'), ('Twitch', 'Twitch'), ('Twitter', 'Twitter'), ('WhatsApp', 'WhatsApp'), ('Youtube', 'Youtube'), ('Github', 'Github')], max_length=100, null=True, verbose_name='icon')),
                ('url', models.URLField(null=True, verbose_name='url')),
                ('is_added', models.BooleanField(default=False, verbose_name='icon added status')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='user.profile')),
            ],
            options={
                'verbose_name': 'Social Icon',
                'verbose_name_plural': 'Social Icons',
            },
        ),
    ]
