# Generated by Django 4.2.2 on 2023-07-12 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='profile',
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
