# Generated by Django 4.2.2 on 2023-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_sociallinks_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='social icon visibility status'),
        ),
    ]
