# Generated by Django 4.2.2 on 2023-07-12 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_sociallinks_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_linkss', to=settings.AUTH_USER_MODEL),
        ),
    ]
