# Generated by Django 4.2.2 on 2023-07-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_sociallinks_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='full name'),
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
