# Generated by Django 4.2.2 on 2023-07-14 21:46

from django.db import migrations, models
import utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_name_delete_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='profile picture', null=True, upload_to=utils.upload.upload_avatar_to, verbose_name='avatar'),
        ),
    ]
